<HomeScreenView>:

    LStackLayout:
        size_hint: 1, 1
        padding: dp(16)

        LLabel:
            text: "Luna Wallet"
            style: "heading_06"
            halign: "center"

        LDivider:

        LGridLayout:
            rows: 1
            size_hint_x: 1
            adaptive: [False, True]

            LAnchorLayout:
                LIcon:
                    icon: "home"

            LAnchorLayout:
                LIconCircular:
                    icon: "wallet"
