<LTextInputLayout>:
    size_hint: 1, None
    inset_color: app.transparent
    bg_color:
        { \
        1: app.field_01, \
        2: app.field_02, \
        }[self.layer_code]
    line_color_focus: app.focus
    inset_width: dp(0.5)
    hover_color:
        { \
        1: app.field_hover_01, \
        2: app.field_hover_02, \
        }[self.layer_code]

<LTextInputLabel>:
    color: app.text_secondary
    style: "label_01"
    font_name: "ibmplexsans"
    pos: [0, self.parent.height + (dp(8))]
    adaptive: [False, True]

<LTextInputHelperText>:
    color: app.text_helper
    style: "helper_text_01"
    font_name: "ibmplexsans"
    pos: [0, - (self.height + dp(4))]
    adaptive: [False, True]

<LTextInputTrailingIconButton>:
    text_color: app.icon_primary
    role: "Large Productive"
    pos: [self.parent.width - (self.width), self.parent.height - (self.height)]

<LTextInput>:
    canvas.after:
        Color:
            rgba: app.border_strong_01
        Line:
            width: dp(0.5)
            points: [self.x + dp(0.25), self.y + dp(0.25), self.right - dp(0.25), self.y + dp(0.25)]

    padding: [dp(16), dp(12), dp(48), dp(12)]
    size_hint_y: None
    font_size: plex_14
    height: max(dp(48), self.minimum_height)
    background_normal: ""
    background_color: app.transparent
    background_active: ""
    hint_text_color: app.text_placeholder
    foreground_color: app.text_primary
    cursor_color: app.text_primary
    password_mask: u"\u2022"
    font_name: "ibmplexsans"
    pos_hint: {'center_y': 0.5}
