<AuthScreenView>:

    LStackLayout:
        size_hint: 1, 1
        spacing: dp(10)
        padding: [dp(10), dp(10), dp(10), dp(10)]

        LBoxLayout:
            orientation: "horizontal"
            adaptive: [False, True]
            
            LButtonGhost:
                icon: "arrow--left"
                spacing: 0
                role: "Large Productive"

            AnchorLayout:
                size_hint: 1, None
                height: icon.height
                anchor_x: "right"
                padding: dp(16)
                AsyncImage:
                    id: icon
                    size_hint: None, None
                    fit_mode: "cover"
                    size: dp(32), dp(32)
                    source: "assets/images/wallet_icon.png"

        LScrollView:
            LoginBoxLayout:

<LoginBoxLayout@LBoxLayout>:
    orientation: "vertical"
    padding: [dp(16), dp(16), dp(16), dp(16)]
    adaptive: [False, True]
    spacing: dp(48)

    LLabel:
        text: "Login"
        style: "heading_06"
        halign: "center"
        color: app.text_primary

    LBoxLayout:
        orientation: "vertical"
        spacing: dp(64)
        adaptive: [False, True]

        LTextInputLayout:
            LTextInput:
                hint_text: "Enter your username"
            LTextInputLabel:
                text: "Username"
            LTextInputHelperText:
                text: "Maximum 10 characters"

        
        LTextInputLayout:

            LTextInput:
                id: pwd_input
                hint_text: "Enter your password"
                password: True
            LTextInputLabel:
                text: "Password"
            LTextInputHelperText:
                text: "Minimum 8 characters"
            LTextInputTrailingIconButton:
                icon: "view--off" if pwd_input.password else "view"
                radius: 0
                on_press:
                    pwd_input.password = (not pwd_input.password)

    LBoxLayout:
        spacing: dp(3)
        adaptive: [False, True]

        LButtonPrimary:
            text: "Login"
            icon: "login"
            role: "Large Productive"
            size_hint_x: 0.5

        LButtonSecondary:
            text: "Signup"
            icon: "user--profile"
            role: "Large Productive"
            size_hint_x: 0.5

    LDivider:

    LLabel:
        text: "or continue with..."
        style: "body_compact_02"
        color: app.text_secondary
        halign: "center"
        adaptive: [False, True]

    GridLayout:
        cols:2
        size_hint: 1, None
        height: self.minimum_height

        AnchorLayout:

            LButtonGhost:
                font_size: plex_48
                text_color: app.text_primary
                icon: "logo--github"
                role: "2XL"
                spacing: 0

        AnchorLayout:

            LButtonGhost:
                font_size: plex_48
                icon: "logo--facebook"
                role: "2XL"
                spacing: 0

