<AuthScreenView>:

    LStackLayout:
        size_hint: 1, 1
        spacing: dp(10)
        padding: [dp(10), dp(10), dp(10), dp(10)]

        LBoxLayout:
            orientation: "horizontal"
            adaptive: [False, True]
            
            LButtonGhost:
                icon: "arrow--left"
                spacing: 0
                role: "Large Productive"

            AnchorLayout:
                size_hint: 1, None
                height: icon.height
                anchor_x: "right"
                padding: dp(16)
                AsyncImage:
                    id: icon
                    size_hint: None, None
                    fit_mode: "cover"
                    size: dp(32), dp(32)
                    source: "assets/images/wallet_icon.png"

        LScrollView:
            LoginBoxLayout:

<LoginBoxLayout@LBoxLayout>:
    orientation: "vertical"
    padding: [dp(16), dp(16), dp(16), dp(16)]
    adaptive: [False, True]
    spacing: dp(48)

    LLabel:
        text: "Unlock"
        style: "heading_06"
        halign: "center"
        color: app.text_primary

    LBoxLayout:
        orientation: "vertical"
        spacing: dp(64)
        adaptive: [False, True]

        LTextInputLayout:

            LTextInput:
                id: pwd_input
                hint_text: "Enter your password"
                password: True
            LTextInputLabel:
                text: "Password"
            LTextInputHelperText:
                text: "Minimum 8 characters"
            LTextInputTrailingIconButton:
                icon: "view--off" if pwd_input.password else "view"
                radius: 0
                on_press:
                    pwd_input.password = (not pwd_input.password)

    LBoxLayout:
        orientation: "vertical"
        spacing: dp(3)
        adaptive: [False, True]

        LButtonPrimary:
            text: "Unlock"
            icon: "unlocked"
            pos_hint: {"center_x": 0.5}
            role: "Large Productive"
