<LLink>:
    orientation: "horizontal"
    size_hint: None, None
    size: self.minimum_width, self.minimum_height
    line_color: self.line_color_focus if (self.cstate == "active") else self.line_color
    line_color_focus: app.focus
    text_color_active: app.text_primary
    text_color_focus: app.link_primary_hover
    text_color_hover: app.link_primary_hover
    text_color_visited: app.link_visited
    text_color_disabled: app.text_disabled
    text_color:
        { \
        "active": self.text_color_active, \
        "disabled": self.text_color_disabled, \
        "normal": app.link_primary, \
        "visited": self.text_color_visited, \
        }[self.cstate]
    line_width: dp(0.5)
    spacing: dp(8)
    padding: [dp(1), dp(1), dp(1), dp(1)]

<LLinkText>:
    markup: True
    size_hint: None, None
    size: self.texture_size
    text_size: None, self.texture_size[1]
    underline: True if (self.parent.cstate == "active") else self.parent.focus
    halign: "center"
    style:
        { \
        "Small": "helper_text_01", \
        "Medium": "body_compact_01", \
        "Large": "body_compact_02", \
        }[self.parent.role]
    -color: self.parent._text_color
    disabled_color: self.parent.text_color_disabled

<LLinkIcon>:
    font_size:
        { \
        "Small": plex_16, \
        "Medium": plex_16, \
        "Large": plex_20, \
        }[self.parent.role]
    pos_hint: {'center_y': 0.5}
    valign: "center"
    disabled_color: self.parent.text_color_disabled
    -color: self.parent._text_color
