<TransactionTile>:
    padding: dp(16)
    spacing: dp(16)
    radius: dp(8)
    adaptive: [False, True]

    LIcon:
        icon: "export" if root.type == "sent" else "download"
        color: app.interactive
        font_size: plex_24
        pos_hint: {"center_y": 0.5}

    LBoxLayout:
        orientation: "vertical"
        adaptive: [False, True]
        spacing: dp(16)

        LLabel:
            text: root.amount
            style: "heading_03"

        LLabel:
            text: root.address
            style: "label_02"
